"use client";

import React, { useState } from "react";
import {
  Badge,
  IconButton,
  Popover,
  Box,
  Stack,
  Typography,
  Button,
} from "@mui/material";
import MailRoundedIcon from "@mui/icons-material/MailRounded";
import ContentCopyRoundedIcon from "@mui/icons-material/ContentCopyRounded";

/**
 * Inbox button + panel that displays newly created users.
 * Each entry contains username/password generated by the Auth service.
 * Works for both single and bulk approve flows.
 */
export default function UserCreationInbox({ logic }) {
  const [anchorEl, setAnchorEl] = useState(null);

  const open = Boolean(anchorEl);
  const { createdUsers, unreadCount, resetUserInbox } = logic;

  const handleOpen = (e) => setAnchorEl(e.currentTarget);
  const handleClose = () => setAnchorEl(null);

  return (
    <>
      {/* Button with badge */}
      <Badge
        color="primary"
        badgeContent={unreadCount}
        invisible={unreadCount === 0}
      >
        <IconButton
          onClick={handleOpen}
          sx={{
            backdropFilter: "blur(12px)",
            background: "rgba(255,255,255,0.5)",
            border: "1px solid rgba(255,255,255,0.7)",
            boxShadow: "0 8px 24px rgba(0,0,0,0.15)",
            "&:hover": {
              background: "rgba(255,255,255,0.65)",
            },
          }}
        >
          <MailRoundedIcon />
        </IconButton>
      </Badge>

      {/* Popover panel */}
      <Popover
        open={open}
        anchorEl={anchorEl}
        onClose={handleClose}
        anchorOrigin={{
          vertical: "bottom",
          horizontal: "right",
        }}
        PaperProps={{
          sx: {
            p: 2,
            borderRadius: "18px",
            width: 340,
            background: "rgba(255,255,255,0.55)",
            backdropFilter: "blur(18px)",
            boxShadow:
              "inset 0 0 0 1px rgba(255,255,255,0.4), 0 12px 40px rgba(0,0,0,0.2)",
          },
        }}
      >
        <Stack spacing={2}>
          <Stack direction="row" justifyContent="space-between">
            <Typography variant="h6" fontWeight={700}>
              Neue Benutzer
            </Typography>

            <Button size="small" onClick={resetUserInbox}>
              Löschen
            </Button>
          </Stack>

          {createdUsers.length === 0 && (
            <Typography sx={{ opacity: 0.6 }}>Keine neuen Benutzer</Typography>
          )}

          <Stack spacing={1.5} sx={{ maxHeight: 300, overflowY: "auto" }}>
            {createdUsers.map((u, index) => (
              <Box
                key={index}
                sx={{
                  p: 1.4,
                  borderRadius: "14px",
                  background: "rgba(255,255,255,0.4)",
                  border: "1px solid rgba(255,255,255,0.3)",
                  backdropFilter: "blur(10px)",
                }}
              >
                <Typography>
                  {u.lastName} {u.firstName}
                </Typography>
                <Typography fontWeight={600}>
                  Einladung: {u.invitationId}
                </Typography>
                <Typography>Username: {u.username}</Typography>
                <Typography>Passwort: {u.password}</Typography>

                <IconButton
                  size="small"
                  onClick={() =>
                    navigator.clipboard.writeText(
                      `${u.username} / ${u.password}`
                    )
                  }
                >
                  <ContentCopyRoundedIcon fontSize="small" />
                </IconButton>
              </Box>
            ))}
          </Stack>
        </Stack>
      </Popover>
    </>
  );
}
